" 基本設定
source ~/dotfiles/.vimrc.basic
" ステータスライン関連
source ~/dotfiles/.vimrc.statusline
" インデント関連
source ~/dotfiles/.vimrc.indent
" 表示関連
source ~/dotfiles/.vimrc.appearance
" 補完関連
"source ~/dotfiles/.vimrc.completion
" タグ関連
"source ~/dotfiles/.vimrc.tags
" 検索関連
source ~/dotfiles/.vimrc.search
" 移動関連
source ~/dotfiles/.vimrc.movement
"ウィンドウ関連
"source ~/dotfiles/.vimrc.window
" カラー関連
source ~/dotfiles/.vimrc.colors
" 編集関連
source ~/dotfiles/.vimrc.edit
" エンコーディング関連
source ~/dotfiles/.vimrc.encoding
